"""Crypto and forex education catalogs — same shape as Indian CATALOG in seed_data.py."""

CRYPTO_CATALOG = [
    {
        'slug': 'crypto-beginner',
        'title': 'Beginner',
        'subtitle': 'Start here — coins, wallets & first paper trades',
        'icon_name': 'school',
        'accent_hex': '#3B82F6',
        'sort_order': 101,
        'articles': [
            {
                'slug': 'what-is-crypto',
                'title': 'What is cryptocurrency? (2025)',
                'summary': 'Bitcoin, altcoins, and how retail investors participate today.',
                'read_minutes': 5,
                'level': 'Beginner',
                'sections': [
                    'Cryptocurrencies are digital assets recorded on public blockchains. Bitcoin is the benchmark; other coins (altcoins) add smart contracts, payments, or DeFi use-cases.',
                    'Prices move 24/7 across global exchanges — there is no NSE/BSE close. Use BTC and ETH as reference points, similar to how Indian investors use NIFTY and SENSEX.',
                    'BullWave Crypto is paper trading: you practise buys and sells with virtual funds. Live exchange execution is off unless the product is explicitly enabled later.',
                    'To start: complete app KYC, understand Wallet vs coin holdings, and keep private keys/seed phrases off screenshots and chat.',
                    'Beginner rule: learn Markets → coin detail → paper buy/sell, start small, and avoid leverage until basics are clear.',
                ],
            },
            {
                'slug': 'wallets-and-exchanges',
                'title': 'Wallets, exchanges & order types',
                'summary': 'Custodial vs self-custody, market vs limit orders.',
                'read_minutes': 4,
                'level': 'Beginner',
                'sections': [
                    'An exchange account holds coins for you (custodial). A self-custody wallet means you control the seed phrase — loss of the phrase is loss of assets.',
                    'Market order: fastest fill at the current book. Limit order: waits for your price. Same idea as Indian equity orders.',
                    'On BullWave, paper orders update your crypto portfolio immediately for practice — they do not move coins on-chain.',
                    'Always check quote currency (usually USDT/USD) and INR conversion shown in the app before sizing a trade.',
                    'Use Notes to record why you bought a coin — discipline starts on day one.',
                ],
            },
            {
                'slug': 'crypto-beginner-checklist',
                'title': 'Beginner checklist before your first crypto trade',
                'summary': 'Practical steps for new crypto learners in India.',
                'read_minutes': 3,
                'level': 'Beginner',
                'sections': [
                    '1. Complete KYC and treat paper Wallet as practice capital only.',
                    '2. Define goal: long-term hold vs short-term trading — different skills and risk.',
                    '3. Never invest money you need for 6 months of expenses.',
                    '4. Start with BTC or ETH paper size; avoid unknown micro-caps initially.',
                    '5. Document entry, target, and invalidation in Notes before buying.',
                    '6. Understand spreads, funding (on perps, later), and INR volatility vs USD pairs.',
                    '7. Read one Crypto Documents topic per week and take a Quiz to reinforce learning.',
                ],
            },
        ],
    },
    {
        'slug': 'crypto-technical_analysis',
        'title': 'Technical Analysis',
        'subtitle': 'Charts, trends, support & resistance',
        'icon_name': 'show_chart',
        'accent_hex': '#22D3EE',
        'sort_order': 102,
        'articles': [
            {
                'slug': 'crypto-ta-basics',
                'title': 'Technical analysis basics',
                'summary': 'Price, volume, and timeframe analysis for BTC and alts.',
                'level': 'Intermediate',
                'sections': [
                    'TA studies historical price/volume — probability, not certainty. Crypto trends can persist or reverse faster than cash equities.',
                    'Identify trend via swing highs/lows. Trade with the dominant trend on your chosen timeframe (4H and 1D are common).',
                    'Support/resistance zones mark areas of prior demand/supply. Watch round numbers (e.g. $100k BTC) as psychological levels.',
                    'Combine TA with strict risk limits — weekend gaps are smaller than stocks, but liquidations can still wipe leveraged positions.',
                ],
            },
            {
                'slug': 'crypto-indicators',
                'title': 'Moving averages & RSI',
                'summary': 'Common indicators on crypto charts.',
                'level': 'Intermediate',
                'sections': [
                    '50/200-period moving averages help gauge medium/long trend context on 4H or daily candles.',
                    'RSI above 70 suggests strong momentum; below 30 weak momentum — context only, especially in strong bull cycles.',
                    'Use BullWave coin charts to practise marking levels before placing a paper trade.',
                ],
            },
        ],
    },
    {
        'slug': 'crypto-fundamentals',
        'title': 'Tokenomics',
        'subtitle': 'Supply, utility & network quality',
        'icon_name': 'analytics',
        'accent_hex': '#10B981',
        'sort_order': 103,
        'articles': [
            {
                'slug': 'tokenomics-basics',
                'title': 'Tokenomics basics',
                'summary': 'Evaluating a coin beyond the chart.',
                'sections': [
                    'Study circulating vs max supply, unlock schedules, and whether the token is used for fees, staking, or governance.',
                    'Compare market cap to sector peers — a high fully diluted value may mean heavy future issuance.',
                    'Quality: transparent team, audits, real usage, and how the chain handles congestion and fees.',
                ],
            },
            {
                'slug': 'reading-onchain',
                'title': 'Reading market structure',
                'summary': 'Dominance, liquidity, and cycle context.',
                'level': 'Intermediate',
                'sections': [
                    'Bitcoin dominance often rises in risk-off phases; alt seasons expand when BTC is stable and liquidity is ample.',
                    'Watch 24h volume and spread — illiquid alts can gap on news.',
                    'Save your thesis in Notes and compare after a catalyst (upgrade, listing, or regulation headline).',
                ],
            },
        ],
    },
    {
        'slug': 'crypto-risk',
        'title': 'Risk Management',
        'subtitle': 'Position size, custody & capital rules',
        'icon_name': 'shield',
        'accent_hex': '#EF4444',
        'sort_order': 104,
        'articles': [
            {
                'slug': 'crypto-position-sizing',
                'title': 'Position sizing 101',
                'summary': 'Risk per trade and concentration limits.',
                'sections': [
                    'Risk 1–2% of paper trading capital per trade based on stop distance — same rule as Indian equities.',
                    'Limit single-coin exposure unless you accept concentration risk. BTC/ETH are still volatile.',
                    'Never share seed phrases. BullWave paper trades do not require on-chain keys.',
                ],
            },
        ],
    },
    {
        'slug': 'crypto-psychology',
        'title': 'Trading Psychology',
        'subtitle': 'Discipline, bias & emotional control',
        'icon_name': 'psychology',
        'accent_hex': '#8B5CF6',
        'sort_order': 105,
        'articles': [
            {
                'slug': 'crypto-psych-basics',
                'title': 'Psychology beats strategy',
                'summary': 'Mindset for 24/7 markets.',
                'sections': [
                    'FOMO on pumps and revenge trading after dumps destroy accounts faster than bad analysis.',
                    'Journal outcomes in Notes — review weekly. Crypto never “closes”, so set screen-time rules.',
                ],
            },
        ],
    },
    {
        'slug': 'crypto-quizzes',
        'title': 'Quizzes',
        'subtitle': 'Test your knowledge',
        'icon_name': 'quiz',
        'accent_hex': '#14B8A6',
        'sort_order': 106,
        'articles': [],
        'quizzes': [
            {
                'slug': 'quiz-crypto-beginner',
                'title': 'Crypto beginner quiz',
                'description': '5 questions on coins, wallets, and safe habits.',
                'questions': [
                    {
                        'prompt': 'Bitcoin is best described as…',
                        'options': [
                            'An NSE-listed stock',
                            'A digital asset on a public blockchain',
                            'A mutual fund NAV',
                            'A bank FD',
                        ],
                        'correct_index': 1,
                        'explanation': 'BTC is a cryptocurrency recorded on its blockchain.',
                    },
                    {
                        'prompt': 'Losing a self-custody seed phrase typically means…',
                        'options': [
                            'The exchange will reset it',
                            'Permanent loss of those coins',
                            'SEBI will recover funds',
                            'Nothing — coins stay in demat',
                        ],
                        'correct_index': 1,
                        'explanation': 'Self-custody has no broker recovery for lost keys.',
                    },
                    {
                        'prompt': 'BullWave Crypto trades in this app are…',
                        'options': [
                            'Live on-chain withdrawals',
                            'Paper / simulated orders',
                            'MCX futures',
                            'IPO applications',
                        ],
                        'correct_index': 1,
                        'explanation': 'The crypto book is paper trading unless live trading is explicitly enabled.',
                    },
                    {
                        'prompt': 'A limit order lets you…',
                        'options': [
                            'Buy at any price instantly',
                            'Set your price and wait for a match',
                            'Avoid all volatility',
                            'Guarantee profit',
                        ],
                        'correct_index': 1,
                        'explanation': 'Limit orders execute at your price or better.',
                    },
                    {
                        'prompt': 'Best first step for a new crypto learner?',
                        'options': [
                            'Max leverage on an unknown alt',
                            'Learn basics and start small on BTC/ETH',
                            'Share your seed in a group chat',
                            'All savings in one meme coin',
                        ],
                        'correct_index': 1,
                        'explanation': 'Education and small size reduce early mistakes.',
                    },
                ],
            },
            {
                'slug': 'quiz-crypto-risk',
                'title': 'Crypto risk quiz',
                'description': 'Position size, custody, and preservation.',
                'questions': [
                    {
                        'prompt': 'Risking 2% per trade refers to…',
                        'options': [
                            '2% of the coin’s price',
                            '2% of total trading capital at stop distance',
                            'Buying 2 coins',
                            'Doubling leverage',
                        ],
                        'correct_index': 1,
                        'explanation': 'Sizing ties risk to total capital.',
                    },
                    {
                        'prompt': 'A stop-loss should be set…',
                        'options': ['After a dump emotionally', 'Before entering', 'Only on weekends', 'Never'],
                        'correct_index': 1,
                        'explanation': 'Plan exits before entries.',
                    },
                    {
                        'prompt': 'You should store a seed phrase…',
                        'options': [
                            'In screenshots and WhatsApp',
                            'Offline, never shared',
                            'In the coin’s Twitter bio',
                            'With your broker RM only',
                        ],
                        'correct_index': 1,
                        'explanation': 'Seeds must stay private and offline.',
                    },
                ],
            },
        ],
    },
]

FOREX_CATALOG = [
    {
        'slug': 'forex-beginner',
        'title': 'Beginner',
        'subtitle': 'Start here — pairs, pips & first paper trades',
        'icon_name': 'school',
        'accent_hex': '#3B82F6',
        'sort_order': 201,
        'articles': [
            {
                'slug': 'what-is-forex',
                'title': 'What is the forex market? (2025)',
                'summary': 'Currency pairs, majors, and how retail traders participate.',
                'read_minutes': 5,
                'level': 'Beginner',
                'sections': [
                    'Forex is the global market for exchanging currencies. A pair such as EUR/USD quotes how many US dollars one euro buys.',
                    'Major pairs (EUR/USD, GBP/USD, USD/JPY, USD/INR context for Indians) are the most liquid — similar to using NIFTY as a reference rather than an illiquid small-cap.',
                    'The market runs nearly 24 hours on weekdays across Tokyo, London, and New York sessions.',
                    'BullWave Forex is paper trading with virtual funds. Quotes may come from live data vendors with a fallback when keys fail.',
                    'Beginner rule: learn pair detail → chart → paper buy/sell, start small, and treat leverage as advanced.',
                ],
            },
            {
                'slug': 'pips-and-lots',
                'title': 'Pips, lots & order types',
                'summary': 'How profit is measured and how orders fill.',
                'read_minutes': 4,
                'level': 'Beginner',
                'sections': [
                    'A pip is the standard increment in a pair’s price (often the 4th decimal on majors; JPY pairs use 2).',
                    'Position size (lot) scales pip value. Larger size means more P&L per pip — and more risk.',
                    'Market order fills immediately; limit waits for your level. Same discipline as Indian equity orders.',
                    'Always check Wallet / paper cash before adding a position. Record the thesis in Notes.',
                ],
            },
            {
                'slug': 'forex-beginner-checklist',
                'title': 'Beginner checklist before your first FX trade',
                'summary': 'Practical steps for new forex learners.',
                'read_minutes': 3,
                'level': 'Beginner',
                'sections': [
                    '1. Complete KYC and treat paper Wallet as practice capital only.',
                    '2. Define goal: hedging INR exposure vs short-term trading.',
                    '3. Keep living expenses out of the trading book.',
                    '4. Start with major pairs; avoid exotic crosses until you understand spreads.',
                    '5. Document entry, target, and invalidation in Notes before buying.',
                    '6. Know the session (London/NY overlap is typically most active).',
                    '7. Read one Forex Documents topic per week and take a Quiz.',
                ],
            },
        ],
    },
    {
        'slug': 'forex-technical_analysis',
        'title': 'Technical Analysis',
        'subtitle': 'Charts, trends, support & resistance',
        'icon_name': 'show_chart',
        'accent_hex': '#22D3EE',
        'sort_order': 202,
        'articles': [
            {
                'slug': 'forex-ta-basics',
                'title': 'Technical analysis basics',
                'summary': 'Price action on major FX pairs.',
                'level': 'Intermediate',
                'sections': [
                    'TA studies historical price — probability, not certainty. FX often respects session highs/lows.',
                    'Identify trend via swing highs/lows. Trade with the dominant trend on H1/H4/D1.',
                    'Support/resistance zones mark prior demand/supply. Round numbers (1.1000 on EUR/USD) matter.',
                    'Combine TA with strict risk limits — news spikes (NFP, RBI, Fed) can skip stops.',
                ],
            },
            {
                'slug': 'forex-indicators',
                'title': 'Moving averages & RSI',
                'summary': 'Common indicators on FX charts.',
                'level': 'Intermediate',
                'sections': [
                    '50/200-period averages help gauge medium/long trend on H4 or daily.',
                    'RSI extremes can persist in strong USD trends — use as context, not a standalone signal.',
                    'Use BullWave pair charts to practise marking levels before a paper trade.',
                ],
            },
        ],
    },
    {
        'slug': 'forex-fundamentals',
        'title': 'Macro Fundamentals',
        'subtitle': 'Rates, inflation & USD drivers',
        'icon_name': 'analytics',
        'accent_hex': '#10B981',
        'sort_order': 203,
        'articles': [
            {
                'slug': 'fx-macro-basics',
                'title': 'Interest rates & currencies',
                'summary': 'Why central banks move forex prices.',
                'sections': [
                    'Higher relative rates often support a currency if growth and inflation are balanced.',
                    'Watch Fed, ECB, BoE, RBI calendars — similar to tracking Indian earnings season for stocks.',
                    'USD strength can pressure EM currencies including INR; majors still lead global liquidity.',
                ],
            },
            {
                'slug': 'reading-fx-news',
                'title': 'Reading the economic calendar',
                'summary': 'What matters in a typical week.',
                'level': 'Intermediate',
                'sections': [
                    'High-impact prints: CPI, employment, policy decisions, GDP.',
                    'Spreads can widen around the release — avoid oversized paper positions into the print until you have a plan.',
                    'Save your pre-event thesis in Notes and compare after the number.',
                ],
            },
        ],
    },
    {
        'slug': 'forex-risk',
        'title': 'Risk Management',
        'subtitle': 'Position size, leverage & capital rules',
        'icon_name': 'shield',
        'accent_hex': '#EF4444',
        'sort_order': 204,
        'articles': [
            {
                'slug': 'forex-position-sizing',
                'title': 'Position sizing 101',
                'summary': 'Risk per trade and leverage caution.',
                'sections': [
                    'Risk 1–2% of paper capital per trade based on stop distance in pips.',
                    'High leverage magnifies both pips and mistakes — keep size small while learning.',
                    'Limit correlated pairs (e.g. EUR/USD and GBP/USD) so one USD move does not double your risk.',
                ],
            },
        ],
    },
    {
        'slug': 'forex-psychology',
        'title': 'Trading Psychology',
        'subtitle': 'Discipline, bias & emotional control',
        'icon_name': 'psychology',
        'accent_hex': '#8B5CF6',
        'sort_order': 205,
        'articles': [
            {
                'slug': 'forex-psych-basics',
                'title': 'Psychology beats strategy',
                'summary': 'Mindset for session-based markets.',
                'sections': [
                    'FOMO during London open and revenge trading after a stop-out destroy accounts faster than bad analysis.',
                    'Journal outcomes in Notes — review weekly. Pick a session you can actually watch.',
                ],
            },
        ],
    },
    {
        'slug': 'forex-quizzes',
        'title': 'Quizzes',
        'subtitle': 'Test your knowledge',
        'icon_name': 'quiz',
        'accent_hex': '#14B8A6',
        'sort_order': 206,
        'articles': [],
        'quizzes': [
            {
                'slug': 'quiz-forex-beginner',
                'title': 'Forex beginner quiz',
                'description': '5 questions on pairs, pips, and safe habits.',
                'questions': [
                    {
                        'prompt': 'EUR/USD quotes…',
                        'options': [
                            'How many euros one dollar buys only on NSE',
                            'The euro versus the US dollar',
                            'Gold in rupees',
                            'Bitcoin versus ether',
                        ],
                        'correct_index': 1,
                        'explanation': 'It is the euro priced in US dollars.',
                    },
                    {
                        'prompt': 'A pip is…',
                        'options': [
                            'A brokerage plan',
                            'A standard price increment on a pair',
                            'A demat holding',
                            'An IPO lot',
                        ],
                        'correct_index': 1,
                        'explanation': 'Pips measure small FX price changes.',
                    },
                    {
                        'prompt': 'BullWave Forex trades in this app are…',
                        'options': [
                            'Live bank FX conversions',
                            'Paper / simulated orders',
                            'MCX crude futures',
                            'Mutual fund SIPs',
                        ],
                        'correct_index': 1,
                        'explanation': 'Forex here is paper trading.',
                    },
                    {
                        'prompt': 'A limit order lets you…',
                        'options': [
                            'Fill at any price instantly',
                            'Set your price and wait for a match',
                            'Remove overnight risk',
                            'Guarantee profit',
                        ],
                        'correct_index': 1,
                        'explanation': 'Limit orders execute at your price or better.',
                    },
                    {
                        'prompt': 'Best first step for a new FX learner?',
                        'options': [
                            'Max leverage on an exotic pair',
                            'Learn majors and start small',
                            'Trade only during RBI holidays',
                            'All capital in one cross',
                        ],
                        'correct_index': 1,
                        'explanation': 'Education and small size reduce early mistakes.',
                    },
                ],
            },
            {
                'slug': 'quiz-forex-risk',
                'title': 'Forex risk quiz',
                'description': 'Position size, leverage, and preservation.',
                'questions': [
                    {
                        'prompt': 'Risking 2% per trade refers to…',
                        'options': [
                            '2% of the pair’s price',
                            '2% of total trading capital at stop distance',
                            'Buying 2 lots always',
                            'Doubling leverage',
                        ],
                        'correct_index': 1,
                        'explanation': 'Sizing ties risk to total capital.',
                    },
                    {
                        'prompt': 'A stop-loss should be set…',
                        'options': ['After a loss emotionally', 'Before entering', 'Only in Tokyo session', 'Never'],
                        'correct_index': 1,
                        'explanation': 'Plan exits before entries.',
                    },
                    {
                        'prompt': 'High leverage mainly…',
                        'options': [
                            'Removes spread',
                            'Magnifies both gains and losses',
                            'Guarantees bank-like returns',
                            'Is required for majors',
                        ],
                        'correct_index': 1,
                        'explanation': 'Leverage scales P&L in both directions.',
                    },
                ],
            },
        ],
    },
]
