# Generated by Django 6.1 on 2026-08-25 07:29

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoApiRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(db_index=True, max_length=40)),
                ('endpoint', models.CharField(max_length=200)),
                ('success', models.BooleanField(default=True)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CryptoNewsArticle',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('summary', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('source', models.CharField(max_length=120)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('category', models.CharField(db_index=True, default='Market Analysis', max_length=40)),
                ('related_assets', models.JSONField(blank=True, default=list)),
                ('external_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='CryptoProviderHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('DOWN', 'Down'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16)),
                ('provider_name', models.CharField(blank=True, default='', max_length=64)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.CharField(blank=True, default='', max_length=500)),
                ('avg_response_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('rate_limit_hits', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('data_freshness_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoAsset',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('market_cap_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('about', models.TextField(blank=True, default='')),
                ('homepage_url', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['market_cap_rank', 'symbol'],
                'indexes': [models.Index(fields=['symbol', 'is_active'], name='crypto_cryp_symbol_d0b1ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='CryptoMarketSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('price_change_24h', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('price_change_percentage_24h', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('high_24h', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('low_24h', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=28, null=True)),
                ('fully_diluted_valuation', models.DecimalField(blank=True, decimal_places=2, max_digits=28, null=True)),
                ('total_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=28, null=True)),
                ('circulating_supply', models.DecimalField(blank=True, decimal_places=4, max_digits=28, null=True)),
                ('total_supply', models.DecimalField(blank=True, decimal_places=4, max_digits=28, null=True)),
                ('max_supply', models.DecimalField(blank=True, decimal_places=4, max_digits=28, null=True)),
                ('ath', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('atl', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('currency', models.CharField(default='usd', max_length=8)),
                ('sparkline_7d', models.JSONField(blank=True, default=list)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='crypto.cryptoasset')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_alerts', models.BooleanField(default=True)),
                ('news_alerts', models.BooleanField(default=True)),
                ('volatility_alerts', models.BooleanField(default=False)),
                ('percent_move_threshold', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoPracticeWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('100000'), max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('last_refilled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_practice_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoPriceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition', models.CharField(choices=[('above', 'Above'), ('below', 'Below'), ('pct_up', 'Percent up'), ('pct_down', 'Percent down')], max_length=16)),
                ('target_value', models.DecimalField(decimal_places=8, max_digits=24)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='crypto.cryptoasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=12, default=Decimal('0'), max_digits=28)),
                ('avg_price', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='crypto.cryptoasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'asset')},
            },
        ),
        migrations.CreateModel(
            name='CryptoTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=12, default=Decimal('0'), max_digits=28)),
                ('price', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('fees', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('exchange', models.CharField(blank=True, default='PAPER', max_length=64)),
                ('external_id', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Completed', max_length=20)),
                ('is_paper', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='crypto.cryptoasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='crypto_cryp_user_id_9a8cd8_idx'), models.Index(fields=['tx_type', 'status'], name='crypto_cryp_tx_type_623c90_idx')],
            },
        ),
        migrations.CreateModel(
            name='CryptoWatchlistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to='crypto.cryptoasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_watchlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'asset')},
            },
        ),
        migrations.CreateModel(
            name='UserMarketPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indian_market_enabled', models.BooleanField(default=True)),
                ('crypto_market_enabled', models.BooleanField(default=False)),
                ('active_market', models.CharField(default='indian', max_length=16)),
                ('has_completed_selection', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['has_completed_selection'], name='crypto_user_has_com_36b1d1_idx')],
            },
        ),
    ]
