from django.urls import path

from .views import (
    CommodityDetailView,
    CommodityHoldingsView,
    CommodityListView,
    CommodityOptionChainView,
    CommodityOrdersView,
    OptionHoldingsView,
    OptionOrdersView,
    DividendsView,
    IpoCalendarView,
    IpoHoldingsView,
    IpoOrdersView,
    MarketLiveView,
    NewsImageProxyView,
    OptionChainView,
    OptionHoldingsView,
    OptionOrdersView,
    PaperTradingOrdersView,
    PortfolioAnalyticsView,
    PortfolioHoldingsView,
    PortfolioOverviewView,
    PortfolioRebalanceCheckView,
    PortfolioRebalanceView,
    PortfolioHealthView,
    PriceAlertsView,
    PriceAlertDetailView,
    NewsAlertsView,
    NewsAlertDetailView,
    ScreenerView,
    SipPlansView,
    SipPlanDetailView,
    StockCandlesView,
    StockNewsView,
    StockQuoteView,
    StockSearchView,
    TradingViewConfigView,
    TradingViewSymbolView,
    TradingViewUdfConfigView,
    TradingViewUdfHistoryView,
    TradingViewUdfSymbolsView,
    TradingViewUdfTimeView,
    TraderNotesView,
    TraderNoteDetailView,
    WatchlistSymbolView,
    WatchlistView,
    CopyTradersView,
    CopyTraderDetailView,
    CopyTraderTradesView,
    CopySubscriptionsView,
    CopySubscriptionDetailView,
    PaperRiskMeterView,
    MarketRiskMeterView,
    PaperCompetitionsView,
    PaperCompetitionDetailView,
    BlockDealsView,
    DarkPoolPrintsView,
)

urlpatterns = [
    path('market/live/', MarketLiveView.as_view(), name='market-live'),
    path('market/tradingview/config/', TradingViewConfigView.as_view(), name='tradingview-config'),
    path('market/tradingview/symbol/<str:symbol>/', TradingViewSymbolView.as_view(), name='tradingview-symbol'),
    path('market/tradingview/udf/config/', TradingViewUdfConfigView.as_view(), name='tradingview-udf-config'),
    path('market/tradingview/udf/time/', TradingViewUdfTimeView.as_view(), name='tradingview-udf-time'),
    path('market/tradingview/udf/symbols/', TradingViewUdfSymbolsView.as_view(), name='tradingview-udf-symbols'),
    path('market/tradingview/udf/history/', TradingViewUdfHistoryView.as_view(), name='tradingview-udf-history'),
    path('market/commodities/', CommodityListView.as_view(), name='commodity-list'),
    path('market/commodities/orders/', CommodityOrdersView.as_view(), name='commodity-orders'),
    path('market/commodities/holdings/', CommodityHoldingsView.as_view(), name='commodity-holdings'),
    path('market/commodities/<str:commodity_id>/options/', CommodityOptionChainView.as_view(), name='commodity-option-chain'),
    path('market/commodities/<str:commodity_id>/', CommodityDetailView.as_view(), name='commodity-detail'),
    path('stocks/search/', StockSearchView.as_view(), name='stock-search'),
    path('stocks/<str:symbol>/quote/', StockQuoteView.as_view(), name='stock-quote'),
    path('stocks/<str:symbol>/candles/', StockCandlesView.as_view(), name='stock-candles'),
    path('watchlist/', WatchlistView.as_view(), name='watchlist'),
    path('watchlist/<str:symbol>/', WatchlistSymbolView.as_view(), name='watchlist-symbol'),
    path('portfolio/overview/', PortfolioOverviewView.as_view(), name='portfolio-overview'),
    path('portfolio/holdings/', PortfolioHoldingsView.as_view(), name='portfolio-holdings'),
    path('portfolio/analytics/', PortfolioAnalyticsView.as_view(), name='portfolio-analytics'),
    path('portfolio/rebalance/', PortfolioRebalanceView.as_view(), name='portfolio-rebalance'),
    path('portfolio/rebalance/check/', PortfolioRebalanceCheckView.as_view(), name='portfolio-rebalance-check'),
    path('portfolio/health/', PortfolioHealthView.as_view(), name='portfolio-health'),
    path('portfolio/risk-meter/', MarketRiskMeterView.as_view(), name='market-risk-meter'),
    path('news/', StockNewsView.as_view(), name='stock-news'),
    path('news/image-proxy/', NewsImageProxyView.as_view(), name='news-image-proxy'),
    path('alerts/', PriceAlertsView.as_view(), name='price-alerts'),
    path('alerts/<uuid:alert_id>/', PriceAlertDetailView.as_view(), name='price-alert-detail'),
    path('news-alerts/', NewsAlertsView.as_view(), name='news-alerts'),
    path('news-alerts/<uuid:alert_id>/', NewsAlertDetailView.as_view(), name='news-alert-detail'),
    path('sip/', SipPlansView.as_view(), name='sip-plans'),
    path('sip/<uuid:plan_id>/', SipPlanDetailView.as_view(), name='sip-plan-detail'),
    path('options/<str:symbol>/chain/', OptionChainView.as_view(), name='option-chain'),
    path('options/orders/', OptionOrdersView.as_view(), name='option-orders'),
    path('options/holdings/', OptionHoldingsView.as_view(), name='option-holdings'),
    path('paper-trading/orders/', PaperTradingOrdersView.as_view(), name='paper-trading'),
    path('screener/', ScreenerView.as_view(), name='screener'),
    path('dividends/', DividendsView.as_view(), name='dividends'),
    path('ipo/calendar/', IpoCalendarView.as_view(), name='ipo-calendar'),
    path('ipo/holdings/', IpoHoldingsView.as_view(), name='ipo-holdings'),
    path('ipo/orders/', IpoOrdersView.as_view(), name='ipo-orders'),
    path('notes/', TraderNotesView.as_view(), name='trader-notes'),
    path('notes/<uuid:note_id>/', TraderNoteDetailView.as_view(), name='trader-note-detail'),
    path('copy-trading/traders/', CopyTradersView.as_view(), name='copy-traders'),
    path('copy-trading/traders/<uuid:trader_id>/', CopyTraderDetailView.as_view(), name='copy-trader-detail'),
    path(
        'copy-trading/traders/<uuid:trader_id>/trades/',
        CopyTraderTradesView.as_view(),
        name='copy-trader-trades',
    ),
    path('copy-trading/subscriptions/', CopySubscriptionsView.as_view(), name='copy-subscriptions'),
    path(
        'copy-trading/subscriptions/<uuid:subscription_id>/',
        CopySubscriptionDetailView.as_view(),
        name='copy-subscription-detail',
    ),
    path('paper-trading/risk-meter/', PaperRiskMeterView.as_view(), name='paper-risk-meter'),
    path('paper-trading/competitions/', PaperCompetitionsView.as_view(), name='paper-competitions'),
    path(
        'paper-trading/competitions/<uuid:competition_id>/',
        PaperCompetitionDetailView.as_view(),
        name='paper-competition-detail',
    ),
    path('market/block-deals/', BlockDealsView.as_view(), name='block-deals'),
    path('market/dark-pool/', DarkPoolPrintsView.as_view(), name='dark-pool'),
]
