# Generated by Django 6.0.7 on 2026-07-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_rename_kyc_fnoelig_status_created_idx_kyc_fnoelig_status_25c40d_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fnoeligibilityrequest',
            new_name='kyc_fnoelig_status_25c40d_idx',
            old_name='kyc_fnoelig_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='kycrequest',
            new_name='kyc_kycrequ_status_0d6aed_idx',
            old_name='kyc_kycrequ_status_created_idx',
        ),
    ]
