# Generated by Django 4.2.30 on 2026-08-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0019_kycprofile_final_kyc_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycprofile',
            name='overall_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
