# Generated by Django 6.0.7 on 2026-07-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_ipo_trading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoditytrade',
            name='realized_pnl_inr',
        ),
        migrations.RemoveField(
            model_name='commoditytrade',
            name='status',
        ),
        migrations.AlterField(
            model_name='stockcandle',
            name='interval',
            field=models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('30m', '30 Minutes'), ('1h', '1 Hour'), ('1d', '1 Day'), ('90d', '90 Days')], default='1d', max_length=5),
        ),
    ]
