# Generated by Django 4.2.30 on 2026-07-11 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0008_tradernote'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(help_text='Symbol or keyword, e.g. RELIANCE or RBI', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('last_matched_at', models.DateTimeField(blank=True, null=True)),
                ('last_matched_title', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='tradernote',
            new_name='stocks_trad_user_id_f74c92_idx',
            old_name='stocks_trad_user_id_c4a8f1_idx',
        ),
        migrations.RenameIndex(
            model_name='tradernote',
            new_name='stocks_trad_user_id_abbc69_idx',
            old_name='stocks_trad_user_id_8e2b0a_idx',
        ),
        migrations.AddField(
            model_name='newsalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='newsalert',
            unique_together={('user', 'keyword')},
        ),
    ]
