# Generated by Django 6.0.7 on 2026-07-13 05:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_newsalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyTraderProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=80)),
                ('handle', models.SlugField(max_length=40, unique=True)),
                ('avatar_color', models.CharField(default='#10B981', max_length=7)),
                ('bio', models.TextField(blank=True, default='')),
                ('strategy_title', models.CharField(max_length=120)),
                ('strategy_summary', models.TextField()),
                ('method_tags', models.JSONField(default=list)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('return_1m', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('return_3m', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('return_1y', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('aum_inr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('min_copy_amount', models.DecimalField(decimal_places=2, default=5000, max_digits=12)),
                ('experience_years', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copy_trader_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-return_3m', '-followers_count'],
            },
        ),
        migrations.CreateModel(
            name='CopyTraderTrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=20)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pnl_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('executed_at', models.DateTimeField()),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='stocks.copytraderprofile')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='CopySubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocation_inr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('copy_ratio', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='active', max_length=10)),
                ('auto_copy', models.BooleanField(default=True)),
                ('copied_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='stocks.copytraderprofile')),
            ],
            options={
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'paused'])), fields=('follower', 'trader'), name='uniq_active_copy_subscription')],
            },
        ),
    ]
