# Generated by Django 6.0.7 on 2026-07-13 05:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_copy_trading'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperCompetition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('invite_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('starting_balance', models.DecimalField(decimal_places=2, default=100000, max_digits=14)),
                ('status', models.CharField(choices=[('open', 'Open'), ('active', 'Active'), ('ended', 'Ended')], default='open', max_length=10)),
                ('duration_days', models.PositiveIntegerField(default=7)),
                ('starts_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_paper_competitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaperCompetitionMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=80)),
                ('equity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pnl', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pnl_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('trades_count', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='stocks.papercompetition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_competition_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pnl_percent', '-equity'],
                'unique_together': {('competition', 'user')},
            },
        ),
    ]
