# Generated by Django 6.0.7 on 2026-07-13 07:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_paper_competition_risk'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockDeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('company_name', models.CharField(max_length=120)),
                ('exchange', models.CharField(default='NSE', max_length=10)),
                ('deal_type', models.CharField(choices=[('block', 'Block Deal'), ('bulk', 'Bulk Deal')], default='block', max_length=10)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('value_cr', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ltp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('premium_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('client_name', models.CharField(blank=True, default='', max_length=120)),
                ('counterparty', models.CharField(blank=True, default='Institutional', max_length=120)),
                ('traded_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-traded_at', '-value_cr'],
            },
        ),
        migrations.CreateModel(
            name='DarkPoolPrint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('company_name', models.CharField(max_length=120)),
                ('venue', models.CharField(default='Dark Pool', max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField()),
                ('value_cr', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vwap', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vs_vwap_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bias', models.CharField(choices=[('buy', 'Buy-biased'), ('sell', 'Sell-biased'), ('mixed', 'Mixed')], default='mixed', max_length=10)),
                ('print_time', models.DateTimeField(db_index=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-print_time', '-value_cr'],
            },
        ),
    ]
