# Generated by Django 4.2.30 on 2026-07-28 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0012_block_deal_dark_pool'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScalperOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instrument_type', models.CharField(choices=[('stock', 'Paper stock'), ('option', 'Option')], max_length=12)),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit')], max_length=12)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.PositiveIntegerField()),
                ('underlying', models.CharField(blank=True, default='', max_length=20)),
                ('asset_class', models.CharField(blank=True, default='', max_length=20)),
                ('strike', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('option_type', models.CharField(blank=True, default='', max_length=2)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('requested_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('limit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('fill_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('trailing_stop_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('high_water_mark', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending entry'), ('active', 'Active position'), ('executed', 'Executed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('exit_reason', models.CharField(blank=True, choices=[('manual', 'Manual'), ('stop_loss', 'Stop loss'), ('target', 'Target'), ('trailing', 'Trailing stop')], default='', max_length=20)),
                ('entry_trade_id', models.CharField(blank=True, default='', max_length=64)),
                ('exit_trade_id', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.CharField(blank=True, default='', max_length=280)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scalper_orders', to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scalper_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'instrument_type'], name='stocks_scalper_status_idx'), models.Index(fields=['user', 'created_at'], name='stocks_scalper_user_idx')],
            },
        ),
    ]
