import '../../models/commodity_model.dart';

/// Offline commodity quotes when backend is unreachable.
class CommodityDataFallback {
  CommodityDataFallback._();

  static const providerLabel = 'Demo commodities (connect backend for live Yahoo feed)';

  static const commodities = [
    CommodityModel(
      id: 'GOLD',
      name: 'Gold',
      shortName: 'Gold',
      category: 'Precious Metals',
      unit: 'USD/oz',
      currency: 'USD',
      icon: 'gold',
      ltp: 3342.50,
      change: 18.40,
      changePercent: 0.55,
      high: 3355.00,
      low: 3320.00,
      previousClose: 3324.10,
    ),
    CommodityModel(
      id: 'SILVER',
      name: 'Silver',
      shortName: 'Silver',
      category: 'Precious Metals',
      unit: 'USD/oz',
      currency: 'USD',
      icon: 'silver',
      ltp: 38.72,
      change: 0.42,
      changePercent: 1.10,
      high: 39.10,
      low: 38.20,
      previousClose: 38.30,
    ),
    CommodityModel(
      id: 'PLATINUM',
      name: 'Platinum',
      shortName: 'Platinum',
      category: 'Precious Metals',
      unit: 'USD/oz',
      currency: 'USD',
      icon: 'platinum',
      ltp: 1024.00,
      change: -6.20,
      changePercent: -0.60,
      high: 1035.00,
      low: 1018.00,
      previousClose: 1030.20,
    ),
    CommodityModel(
      id: 'CRUDE_OIL',
      name: 'Crude Oil (WTI)',
      shortName: 'Crude Oil',
      category: 'Energy',
      unit: 'USD/bbl',
      currency: 'USD',
      icon: 'oil',
      ltp: 78.45,
      change: 1.12,
      changePercent: 1.45,
      high: 79.20,
      low: 77.10,
      previousClose: 77.33,
    ),
    CommodityModel(
      id: 'BRENT_OIL',
      name: 'Brent Crude',
      shortName: 'Brent',
      category: 'Energy',
      unit: 'USD/bbl',
      currency: 'USD',
      icon: 'oil',
      ltp: 82.10,
      change: 0.95,
      changePercent: 1.17,
      high: 83.00,
      low: 80.80,
      previousClose: 81.15,
    ),
    CommodityModel(
      id: 'NATURAL_GAS',
      name: 'Natural Gas',
      shortName: 'Nat. Gas',
      category: 'Energy',
      unit: 'USD/MMBtu',
      currency: 'USD',
      icon: 'gas',
      ltp: 2.84,
      change: -0.06,
      changePercent: -2.07,
      high: 2.92,
      low: 2.80,
      previousClose: 2.90,
    ),
    CommodityModel(
      id: 'COPPER',
      name: 'Copper',
      shortName: 'Copper',
      category: 'Industrial Metals',
      unit: 'USD/lb',
      currency: 'USD',
      icon: 'copper',
      ltp: 4.52,
      change: 0.03,
      changePercent: 0.67,
      high: 4.58,
      low: 4.46,
      previousClose: 4.49,
    ),
    CommodityModel(
      id: 'ALUMINUM',
      name: 'Aluminum',
      shortName: 'Aluminum',
      category: 'Industrial Metals',
      unit: 'USD/ton',
      currency: 'USD',
      icon: 'metal',
      ltp: 2485.00,
      change: 12.00,
      changePercent: 0.49,
      high: 2498.00,
      low: 2465.00,
      previousClose: 2473.00,
    ),
  ];
}
