# Generated by Django 4.2.30 on 2026-07-28 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationErrorEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('backend', 'Backend'), ('flutter', 'Flutter')], max_length=20)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='error', max_length=20)),
                ('fingerprint', models.CharField(max_length=64)),
                ('logger_name', models.CharField(blank=True, default='', max_length=160)),
                ('message', models.CharField(max_length=500)),
                ('exception_type', models.CharField(blank=True, default='', max_length=160)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('method', models.CharField(blank=True, default='', max_length=12)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_application_errors', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_errors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['status', 'last_seen_at'], name='adminpanel_error_status_idx'), models.Index(fields=['source', 'last_seen_at'], name='adminpanel_error_source_idx'), models.Index(fields=['severity', 'last_seen_at'], name='adminpanel_error_severity_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='applicationerrorevent',
            constraint=models.UniqueConstraint(fields=('source', 'fingerprint'), name='adminpanel_unique_error_fingerprint'),
        ),
    ]
