# Generated by Django 4.2.30 on 2026-07-28 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_applicationerrorevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('support_ticket', 'Support ticket'), ('kyc_review', 'KYC review'), ('payment_failed', 'Payment failed'), ('payout_failed', 'Payout failed'), ('critical_error', 'Critical error'), ('new_user', 'New user')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('reference_id', models.CharField(blank=True, default='', max_length=80)),
                ('action_tab', models.CharField(blank=True, default='', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', 'created_at'], name='adminpanel_notif_read_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='adminnotification',
            constraint=models.UniqueConstraint(fields=('kind', 'reference_id'), name='adminpanel_unique_notification_ref'),
        ),
    ]
