from django.urls import path

from .views import (
    AadhaarDecisionView,
    AdminLoginView,
    AdminMeView,
    AuditLogView,
    BankProfileDecisionView,
    BankReviewDecisionView,
    BankReviewListView,
    CommoditiesReportView,
    DashboardView,
    ErrorBulkDeleteView,
    ErrorDetailView,
    ErrorLogView,
    FinanceReportView,
    FuturesReportView,
    AdminBroadcastListView,
    AdminNotificationListView,
    AdminNotificationReadAllView,
    AdminNotificationReadView,
    AdminSupportTicketDetailView,
    AdminSupportTicketListView,
    FinalKycDecisionView,
    FnoReviewDecisionView,
    FnoReviewListView,
    IdentityUpiDecisionView,
    KycOverviewView,
    KycProfileListView,
    OptionsReportView,
    PanReviewDecisionView,
    PanReviewListView,
    SelfieReviewDecisionView,
    SelfieReviewListView,
    StocksReportView,
    UserBlockView,
    UserDeleteView,
    UserDetailView,
    UserListView,
)


urlpatterns = [
    path('auth/login/', AdminLoginView.as_view(), name='admin-panel-login'),
    path('auth/me/', AdminMeView.as_view(), name='admin-panel-me'),
    path('dashboard/', DashboardView.as_view(), name='admin-panel-dashboard'),
    path('errors/', ErrorLogView.as_view(), name='admin-panel-errors'),
    path('errors/bulk-delete/', ErrorBulkDeleteView.as_view(), name='admin-panel-errors-delete'),
    path('errors/<uuid:pk>/', ErrorDetailView.as_view(), name='admin-panel-error-detail'),
    path(
        'errors/<uuid:pk>/<str:action>/',
        ErrorDetailView.as_view(),
        name='admin-panel-error-action',
    ),
    path('users/', UserListView.as_view(), name='admin-panel-users'),
    path('users/<uuid:user_id>/', UserDetailView.as_view(), name='admin-panel-user-detail'),
    path('users/<uuid:user_id>/<str:action>/', UserBlockView.as_view(), name='admin-panel-user-block'),
    path('users/<uuid:user_id>/delete/', UserDeleteView.as_view(), name='admin-panel-user-delete'),
    path('kyc/overview/', KycOverviewView.as_view(), name='admin-panel-kyc-overview'),
    path('kyc/profiles/', KycProfileListView.as_view(), name='admin-panel-kyc-profiles'),
    path('trading/stocks/', StocksReportView.as_view(), name='admin-panel-trading-stocks'),
    path('trading/commodities/', CommoditiesReportView.as_view(), name='admin-panel-trading-commodities'),
    path('trading/futures/', FuturesReportView.as_view(), name='admin-panel-trading-futures'),
    path('trading/options/', OptionsReportView.as_view(), name='admin-panel-trading-options'),
    path('kyc/pan/', PanReviewListView.as_view(), name='admin-panel-pan-reviews'),
    path(
        'kyc/pan/<uuid:pk>/<str:decision>/',
        PanReviewDecisionView.as_view(),
        name='admin-panel-pan-decision',
    ),
    path('kyc/fno/', FnoReviewListView.as_view(), name='admin-panel-fno-reviews'),
    path(
        'kyc/fno/<uuid:pk>/<str:decision>/',
        FnoReviewDecisionView.as_view(),
        name='admin-panel-fno-decision',
    ),
    path('kyc/bank/', BankReviewListView.as_view(), name='admin-panel-bank-reviews'),
    path(
        'kyc/bank/<uuid:pk>/<str:decision>/',
        BankReviewDecisionView.as_view(),
        name='admin-panel-bank-decision',
    ),
    path('kyc/selfie/', SelfieReviewListView.as_view(), name='admin-panel-selfie-reviews'),
    path(
        'kyc/selfie/<uuid:user_id>/<str:decision>/',
        SelfieReviewDecisionView.as_view(),
        name='admin-panel-selfie-decision',
    ),
    path(
        'kyc/aadhaar/<uuid:user_id>/<str:decision>/',
        AadhaarDecisionView.as_view(),
        name='admin-panel-aadhaar-decision',
    ),
    path(
        'kyc/upi/<uuid:user_id>/<str:decision>/',
        IdentityUpiDecisionView.as_view(),
        name='admin-panel-upi-decision',
    ),
    path(
        'kyc/bank-profile/<uuid:user_id>/<str:decision>/',
        BankProfileDecisionView.as_view(),
        name='admin-panel-bank-profile-decision',
    ),
    path(
        'kyc/final/<uuid:user_id>/<str:decision>/',
        FinalKycDecisionView.as_view(),
        name='admin-panel-final-kyc-decision',
    ),
    path('reports/finance/', FinanceReportView.as_view(), name='admin-panel-finance'),
    path('audit/', AuditLogView.as_view(), name='admin-panel-audit'),
    path('notifications/', AdminNotificationListView.as_view(), name='admin-panel-notifications'),
    path(
        'notifications/read-all/',
        AdminNotificationReadAllView.as_view(),
        name='admin-panel-notifications-read-all',
    ),
    path(
        'notifications/<uuid:pk>/<str:action>/',
        AdminNotificationReadView.as_view(),
        name='admin-panel-notification-action',
    ),
    path('support/tickets/', AdminSupportTicketListView.as_view(), name='admin-panel-support-tickets'),
    path(
        'support/tickets/<uuid:ticket_id>/',
        AdminSupportTicketDetailView.as_view(),
        name='admin-panel-support-ticket-detail',
    ),
    path(
        'support/tickets/<uuid:ticket_id>/<str:action>/',
        AdminSupportTicketDetailView.as_view(),
        name='admin-panel-support-ticket-action',
    ),
    path('broadcasts/', AdminBroadcastListView.as_view(), name='admin-panel-broadcasts'),
]
